#! /bin/sh

set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later


export KVALOBS=$HOME
export PERL5LIB=$HOME/lib/perl
export METADIR=$HOME/src/kvalobs_metadata



#echo "KVALOBS=$KVALOBS"
#echo "METADIR=$METADIR"


DUMPDIR=$KVALOBS/var/log/stkv_tabledump
mkdir -p  $DUMPDIR

## PRODUCTION
$KVALOBS/bin/stkv_cron/station2kvalobs.pl 365 > $DUMPDIR/station.utf-8
$KVALOBS/bin/stkv_cron/obs_pgm2kvalobs_new.pl 365 > $DUMPDIR/obs_pgm.out
$KVALOBS/bin/stkv_cron/param2kvalobs.pl       > $DUMPDIR/param.utf-8
$KVALOBS/bin/stkv_cron/message_format_stdump.pl > $DUMPDIR/message_format.utf-8

for TABLE in param station message_format
do
  iconv -f utf-8 -t latin1  $DUMPDIR/$TABLE.utf-8 > $DUMPDIR/$TABLE.latin1
  if [ -n "$1" ]; then 
      #echo "latin1"
      cp -p $DUMPDIR/$TABLE.latin1  $DUMPDIR/$TABLE.out
  else
      #echo "utf-8"
      cp -p $DUMPDIR/$TABLE.utf-8   $DUMPDIR/$TABLE.out
  fi
done

## COPY TO METADIR    
for TABLE in param obs_pgm station
do       
    if ! diff -q  $DUMPDIR/$TABLE.out  $METADIR/share/metadata/$TABLE/$TABLE.out
    then
	if [ -s $DUMPDIR/$TABLE.out ]; then
	    cp -upv $DUMPDIR/$TABLE.out $METADIR/share/metadata/$TABLE/$TABLE.out
	else
            echo "Empty file:  $DUMPDIR/$TABLE.out"
        fi
    fi
done


if ! diff -q $DUMPDIR/message_format.out $METADIR/share/metadata/types/types.out
then
    cp -upv $DUMPDIR/message_format.out $METADIR/share/metadata/types/types.out
fi
