#! /bin/sh

set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later


export KVALOBSDEV=$HOME
export METADIR=$HOME/src/kvalobs_metadata
export PERL5LIB=$KVALOBSDEV/lib/perl

if [ -f  $KVALOBSDEV/etc/st-info-sys.conf ]; then
   source $KVALOBSDEV/etc/st-info-sys.conf
else
   echo "Missing file:  $KVALOBSDEV/etc/st-info-sys.conf"
   exit 1
fi


stPGUSER=$PGUSER
stPGNAME=$PGNAME
stPGHOST=$PGHOST
stPGPORT=$PGPORT

PGPASSWORD=$PGPASSWD



## ** Subroutines **
err_msg() {
    echo "stPGUSER = "$PGUSER
    echo "stPGNAME = "$PGNAME
    echo "stPGHOST = "$PGHOST
    echo "stPGPORT = "$PGPORT
    ERROR_MSG="$1 Avslutter..."
    # echo -e `date` "\t$ERROR_MSG" >> $LOGFILE
    echo $ERROR_MSG
    exit 1
}


   
check_if_empty_table() {
   NUM_ROWS=`psql -h $stPGHOST -U $stPGUSER -d $stPGNAME -t -c "select count(*) from $1"`
   if [ ! $? ]; then
       err_msg "ERROR: psql-sjekk om tabellen $1 er tom feilet!"
   elif [ $NUM_ROWS -eq 0 ]; then
       err_msg "ERROR: tabellen $1 er tom."
   fi
}

#echo "KVALOBSDEV=$KVALOBSDEV"
#echo "METADIR=$METADIR"


DUMPDIR=$KVALOBSDEV/var/log/stkv_tabledump
mkdir -p  $DUMPDIR

for TABLE in station
do
    check_if_empty_table $TABLE
done

## PRODUCTION
$KVALOBSDEV/bin/stkv_cron/stinfosys2kvalobs.pl > $DUMPDIR/station.out


## COPY TO METADIR    
for TABLE in station # param
do       
    if ! diff -q  $DUMPDIR/$TABLE.out  $METADIR/share/metadata/$TABLE/$TABLE.out
    then
	if [ -s $DUMPDIR/$TABLE.out ]; then
	    cp -upv $DUMPDIR/$TABLE.out $METADIR/share/metadata/$TABLE/$TABLE.out 
	else
	    echo "Empty file:  $DUMPDIR/$TABLE.out"
	    exit 1
	fi
    fi
done