#! /bin/sh

set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later


if [ -f $HOME/.kvalobs ]; then
   source $HOME/.kvalobs
else
   echo "Missing file: $HOME/.kvalobs"
   exit 1
fi


if [ -f  $KVALOBS/etc/st-info-sys.conf ]; then
   source $KVALOBS/etc/st-info-sys.conf
else
   echo "Missing file:  $KVALOBS/etc/st-info-sys.conf"
   exit 1
fi


stPGUSER=$PGUSER
stPGNAME=$PGNAME
stPGHOST=$PGHOST
stPGPORT=$PGPORT

PGPASSWORD=$PGPASSWD



## ** Subroutines **
err_msg() {
    echo "stPGUSER = "$PGUSER
    echo "stPGNAME = "$PGNAME
    echo "stPGHOST = "$PGHOST
    echo "stPGPORT = "$PGPORT
    ERROR_MSG="$1 Avslutter..."
    # echo -e `date` "\t$ERROR_MSG" >> $LOGFILE
    echo $ERROR_MSG
    exit 1
}


   
check_if_empty_table() {
   NUM_ROWS=`psql -h $stPGHOST -U $stPGUSER -d $stPGNAME -t -c "select count(*) from $1"`
   if [ ! $? ]; then
       err_msg "ERROR: psql-sjekk om tabellen $1 er tom feilet!"
   elif [ $NUM_ROWS -eq 0 ]; then
       err_msg "ERROR: tabellen $1 er tom."
   fi
}

#echo "KVALOBS=$KVALOBS"
#echo "METADIR=$METADIR"


DUMPDIR=$KVALOBS/var/log/stkv_tabledump
mkdir -p  $DUMPDIR

## PRODUCTION
$KVALOBS/bin/stkv_cron/stinfosys2kvalobs.pl > $DUMPDIR/station.out

for TABLE in param obs_pgm message_format
do
    check_if_empty_table $TABLE
    psql -h $stPGHOST -U $stPGUSER -d $stPGNAME -t -c "\copy $TABLE to $DUMPDIR/$TABLE.out USING DELIMITERS '|'"
  
    if [ ! $? ]; then
	err_msg "ERROR: Dumping av tabell $TABLE mislyktes!"
    fi    
done


## COPY TO METADIR    
for TABLE in station param obs_pgm
do       
    if ! diff -q  $DUMPDIR/$TABLE.out  $METADIR/share/metadata/$TABLE/$TABLE.out
    then
	cp -upv $DUMPDIR/$TABLE.out $METADIR/share/metadata/$TABLE/$TABLE.out	
    fi
done


if ! diff -q $DUMPDIR/message_format.out $METADIR/share/metadata/types/types.out
then
    cp -upv $DUMPDIR/message_format.out $METADIR/share/metadata/types/types.out
fi
