#!/usr/bin/perl -w


use POSIX;
use strict;
use dbQC;

#my $kvalobs;
#my $scriptpath;
my $path= get_algorithms_path();

#if(!$ENV{"KVALOBS"}){
#   printf("Missing variable KVALOBS, using . !\n");
#   $kvalobs=".";
#}else{
#    $kvalobs=$ENV{"KVALOBS"};
#}

#$scriptpath="$kvalobs/share/kvalobs/dbscript";


#$ENV{"PATH"}="$scriptpath:$ENV{\"PATH\"}";
#printf("PATH: %s\n", $ENV{"PATH"});
#printf("system(algorithm_all ins $path)\n");

system("algorithm_all ins $path");


