#!/usr/bin/perl -w


use POSIX;
use strict;
use dbQC;


my $path= get_checks_manual_path();

my @subd = qw( QC1-2 QC1-6  QC1_rest QC2d );

chdir($path);
my $expath=getenv('LIBEXECDIR');
foreach my $sub (@subd){
  system("$expath/checks_all ins $sub");
  chdir($path);
}

