#!/usr/bin/perl -w

use POSIX;
use strict;
use dbQC;

my $path= get_station_param_manual_path();
my @subd = qw( QC1-2 QC1-6  QC1_rest  QC2d );

chdir($path);
foreach my $sub (@subd){
  system("station_param_all ins  $sub");
  chdir($path);
}


