#!/usr/bin/perl -w

use POSIX;
use strict;
use dbQC;
use intodb;

my $hk=$ENV{"KVALOBS"};
my $metadata=$hk . "/share/kvalobs/metadata";

my $path= "$metadata/hist_station";

static_intodb( $path,"station","station.out",'|'); 
   
