#!/usr/bin/perl -w

use POSIX;
use strict;
#use dbQC;
use trim;
use intodb;

my $metadata=`kvconfig --datadir`; 
$metadata = trim( $metadata )  . "/kvalobs/metadata";
my $path= "$metadata/hist_obs_pgm";

all_intodb( $path,"obs_pgm","obs_pgm.out",'|');
