#! /bin/sh

## Script to update metadata tables in Kvalobs.


set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later


if ! [ $PGHOST ]; then
    echo "PGHOST er ikke satt! Avslutter..."
    exit 1
fi


## ** Global variables **
if ! [ $KVALOBS ]; then
   MYPATH="."
   KVALOBS=$HOME
else
   MYPATH="$KVALOBS/bin/dbscript"
fi

PERL5LIB="$KVALOBS/lib/perl"

if [ -z "$PGPASSWORD" ]; then
    PGPASSWORD=`grep dbpass ~/.kvpasswd | sed -e 's/ *dbpass *//'`
fi

PGNAME=kvalobs
PGUSER=kvalobs
PGTARGET="-h $PGHOST -d $PGNAME -U $PGUSER"

DUMPDIR="$KVALOBS/var/log/tabledump"
LOGFILE="$DUMPDIR/table_update.log"


## ** Subroutines **
err_msg() {
    ERROR_MSG="$1 Avslutter..."
    echo -e `date` "\t$ERROR_MSG" >> $LOGFILE
    echo $ERROR_MSG
    exit 1
}
    
check_if_empty_table() {
   NUM_ROWS=`psql $PGTARGET -t -c "select count(*) from $1"`
   if [ ! $? ]; then
       err_msg "ERROR: psql-sjekk om tabellen $1 er tom feilet!"
   elif [ $NUM_ROWS -eq 0 ]; then
       err_msg "ERROR: tabellen $1 er tom."
   fi
}


## ** MAIN **
mkdir -pv $DUMPDIR


echo "Oppdaterer tabellene param model qcx_info"
for TABLE in param model qcx_info
do
    psql  $PGTARGET -c "\copy $TABLE to $DUMPDIR/$TABLE.out USING DELIMITERS '|'"
    if [ ! $? ]; then
	err_msg "ERROR: Dumping av tabell $TABLE mislyktes!"
    fi
       
    if ! diff -q  $DUMPDIR/$TABLE.out $KVALOBS/share/kvalobs/metadata/$TABLE/$TABLE.out
    then
	$MYPATH/run_$TABLE 
	if [ ! $? ]; then
	    err_msg "ERROR: $MYPATH/run_$TABLE mislyktes!"
	fi
	echo -e `date` "\t$TABLE updated" >> $LOGFILE
	check_if_empty_table $TABLE
    fi
done


echo "HISTORISK oppdaterer tabellene obs_pgm station types"
for TABLE in obs_pgm station  types
do
    psql  $PGTARGET -c "\copy $TABLE to $DUMPDIR/$TABLE.out USING DELIMITERS '|'"
    if [ ! $? ]; then
	err_msg "ERROR: Dumping av tabell $TABLE mislyktes!"
    fi
       
    if ! diff -q  $DUMPDIR/$TABLE.out $KVALOBS/share/kvalobs/metadata/hist_$TABLE/$TABLE.out
    then
	$MYPATH/hist_run_$TABLE 
	if [ ! $? ]; then
	    err_msg "ERROR: $MYPATH/hist_run_$TABLE mislyktes!"
	fi
	echo -e `date` "\t$TABLE updated" >> $LOGFILE
	check_if_empty_table $TABLE
    fi
done


echo "Oppdaterer tabellene  algorithms checks station_param"
for TABLE in algorithms checks station_param
do
    psql -a $PGTARGET -c "delete from $TABLE"
    if [ ! $? ]; then
	err_msg "ERROR: Sletting fra $TABLE mislyktes!"
    fi
done


# Tables  algorithms, checks and station_param need several scripts
# for updating
for COMMAND in "run_QC1-1 all"  "run_QC1-3 all" \
    "run_QC1-4 all"  "checks_auto QC1-1_checks"  "checks_auto QC1-3a_checks" \
    "checks_auto  QC1-3b_checks" "checks_auto  QC1-4_checks"
do
    $MYPATH/$COMMAND
    if [ ! $? ]; then
        err_msg "ERROR: $COMMAND mislyktes!"
    fi
done 


for COMMAND in run_algorithm_all run_station_param_all  run_checks_all
do
    echo "$MYPATH/$COMMAND > $DUMPDIR/$COMMAND.out"
    $MYPATH/$COMMAND > $DUMPDIR/$COMMAND.out
    if [ ! $? ]; then
        err_msg "ERROR: $COMMAND mislyktes!"
    fi
done  


echo "Sjekker antall linjer i tabellene algorithms checks station_param"
for TABLE in algorithms checks station_param
do
    check_if_empty_table $TABLE
done
