#! /bin/sh

METADATA="share/kvalobs/metadata"

DESTINATION=
DIRECTORIES="$METADATA/model             \
             $METADATA/obs_pgm           \
             $METADATA/operator          \
             $METADATA/param             \
             $METADATA/qcx_info          \
             $METADATA/reference_station \
             $METADATA/station           \
             $METADATA/station_param/station_param_auto\
	     $METADATA/station_param/station_param_manual/QC1-2\
             $METADATA/station_param/station_param_manual/QC1-6\
             $METADATA/station_param/station_param_manual/QC1_rest\
	     $METADATA/station_param/station_param_manual/QC2d\
             $METADATA/types             \
	     $METADATA/algorithms        \
	     $METADATA/checks/checks_auto \
             $METADATA/checks/checks_manual/QC1-2 \
             $METADATA/checks/checks_manual/QC1-6\
             $METADATA/checks/checks_manual/QC1_rest\
             $METADATA/checks/checks_manual/QC2d"

FILES=

#Prepare the install

mkdir -p "$METADATA"

if ! [ -d $METADATA ]; then
   echo "Cant create directory `pwd`/$METADATA"
   exit 1
fi

MYTOP=`pwd`

cd $METADATA

for DIR in `ls -1 $MYTOP` ; do
  if [ -d "$MYTOP/$DIR" ]; then
      if [ "$DIR" != "share" -a "$DIR" != "CVS" ]; then
        if ! [ -L $DIR ]; then
           ln -s "$MYTOP/$DIR" "$DIR"
        fi
     fi
  fi
done
   
cd $MYTOP

#Do the install
. $KVDIR/conf/INSTALL.conf


















