#! /bin/sh

set -e  # Exit if a simple shell command fails

export HOME=/metno/kvalobs
export PGHOST=localhost
export PGPORT=5432

export METADIR=$HOME/kvoss_intern/kvmeta

LIBEXECDIR=/usr/lib/kvalobs-metadata/bin

echo '/metno/kvalobs/bin/git_pull:'
/metno/kvalobs/bin/git_pull

$LIBEXECDIR/run_klima2kvalobs

mkdir -pv $HOME/var/log

$LIBEXECDIR/kvinstall_metadata

$LIBEXECDIR/run_QC1-1_all

# echo "run_klima2kvalobs_all `date +'%Y-%m-%d'`" > $HOME/var/log/run_klima2kvalobs_all.finished_log
$HOME/bin/monitor/monitor_log.sh run_klima2kvalobs_all
