#! /bin/bash

## Script to update metadata tables in Kvalobs.

set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later

PATH="/metno/kvalobs/bin:/metno/kvalobs/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

export PATH

USER=kvalobs

METALOG="http://metakvalobs.met.no/kvalobs/view_auto.log"
wget -O - $METALOG > $HOME/log/view_auto.log
MYVAR=`tail -n 1 $HOME/log/view_auto.log`
if [ $MYVAR = "Fortsett" ]; then
    echo "Oppdateringen starter"
    # exit 0
else
    echo "Oppdateringen blir ikke utført i dag"
    cat  $HOME/log/view_auto.log
    exit 0
fi


echo "Starting kvget-metadata_insert_update_delete:"
if /metno/kvalobs/bin/kvget-metadata_insert_update_delete; then
    echo "OK /metno/kvalobs/bin/kvget-metadata_insert_update_delete"
else
    echo "FAILED /metno/kvalobs/bin/kvget-metadata_insert_update_delete"
    exit 1
fi

if kvstop; then
    echo "OK kvstop"
else
    echo "FAILED kvstop"
    # exit 1
fi

if kvstart; then
    echo "OK kvstart"
else
    echo "FAILED kvstart"
fi

echo "kvget-metadata_insert_update_delete_all `date +'%Y-%m-%d'`" > $HOME/log/kvget-metadata_insert_update_delete_all.finished_log
