#! /bin/sh

## Script to update metadata tables in Kvalobs.

set -a  # export variables to the environment of subsequent commands
set -e  # Exit if a simple shell command fails
#set -x  # for debugging, remove later

export LANG=en_US.latin1

PGDATABASE=kvalobs
PGUSER=kvalobs


## ** Subroutines **
assert_table_not_empty() {
	NUM_ROWS=`psql -t -c "select count(*) from $1"`
	if [ $NUM_ROWS -eq 0 ]; then
		echo "ERROR: tabellen $1 er tom."
		exit 1
	fi
}

#METAGET=/usr/share/kvalobs/metaget
METAGET=/usr/share/kvalobs

KRO="kro"
if [ -f $HOME/.kro  ]; then
    KRO=`cat $HOME/.kro`
fi


if [ -n "$1" ]; then
   METAGET=$PWD
   echo "argumentet er $1"
   # tar xvvjf $1
else
    DUMPDIR="$METAGET/dumpdir"
    mkdir -p -m700 $DUMPDIR
    mkdir -p -m700 "$METAGET/utesperring"
    #cd "$METAGET/dumpdir"
    LOGDIR=$HOME/log/utesperring
    mkdir -p $LOGDIR

 for FILE in utesperring.sql utesperring_update.sql
 do
    wget -O - http://$KRO/$FILE > $DUMPDIR/$FILE
    if ! [ -s $DUMPDIR/$FILE ]; then
       echo "Filen $DUMPDIR/$FILE er tom" > $LOGDIR/$FILE.log
       exit 1
    fi  

    echo "$DUMPDIR/$FILE"
    echo "$METAGET/utesperring/$FILE"

    if ! diff -q  $DUMPDIR/$FILE  $METAGET/utesperring/$FILE
    then
       if [ -f $METAGET/utesperring/$FILE  ]; then
            mv -uv $METAGET/utesperring/$FILE $METAGET/utesperring/$FILE.old
       fi 
       cp -pv $DUMPDIR/$FILE $METAGET/utesperring/$FILE
       PSQL=psql
       #psql -f /metno/kvalobs/insert_qc1_0.sql
       $PSQL -f $METAGET/utesperring/$FILE
       #cp -pv  $METAGET/utesperring/$FILE $HOME/insert_qc1_0.sql
    fi
  done
fi
